#### Numpy

- Pandas : https://pandas.pydata.org/
- Numpy : https://numpy.org/

- 수치해석, 수학적 처리, 통계 등을 위한 라이브러리(모듈) - Scipy, Pandas, Matploplib

In [4]:
!pip list

Package           Version
----------------- -------
asttokens         2.2.1
backcall          0.2.0
colorama          0.4.6
comm              0.1.3
debugpy           1.6.7
decorator         5.1.1
et-xmlfile        1.1.0
executing         1.2.0
Faker             18.11.1
ipykernel         6.23.2
ipython           8.14.0
jedi              0.18.2
jupyter_client    8.2.0
jupyter_core      5.3.1
matplotlib-inline 0.1.6
nest-asyncio      1.5.6
numpy             1.25.0
openpyxl          3.1.2
packaging         23.1
pandas            2.0.2
parso             0.8.3
pickleshare       0.7.5
pip               23.1.2
platformdirs      3.7.0
prompt-toolkit    3.0.38
psutil            5.9.5
pure-eval         0.2.2
Pygments          2.15.1
PyMySQL           1.0.3
python-dateutil   2.8.2
pytz              2023.3
pywin32           306
pyzmq             25.1.0
setuptools        65.5.0
six               1.16.0
stack-data        0.6.2
tornado           6.3.2
traitlets         5.9.0
tzdata            2023.3
w

In [2]:
!pip install numpy

In [3]:
!pip install pandas

In [6]:
# import
import pandas as pd
import numpy as np

#### Numpy를 쓰는 이유

- python 리스트를 만들면 (1,000,000건) - 260ms
- numpy 배열을 만들면 (1,000,000건) - 34.3ms (8배정도 빠름)

In [7]:
py_list = list(range(1_000_000)) # 100만건 리스트 만들기

In [8]:
np_arr = np.arange(1_000_000)

In [10]:
## python 리스트 사용
%timeit for _ in range(10): py_list2 = py_list * 2

143 ms ± 3.38 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
## numpy 리스트 사용
%timeit for _ in range(10): np_arr2 = np_arr * 2

13.2 ms ± 211 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


##### numpy로 배열 생성, 연산 등

- 파이썬 리스트는 +(리스트끼리),*(숫자만) 연산 밖에 없음
- 행렬(벡터)로 연산을 하고 싶으면 numpy 배열로 형변환 후에 처리할 것

In [12]:
# 1차원 배열
np_arr1 = np.array([1,3,5])
np_arr1

array([1, 3, 5])

In [18]:
# 2차원 배열
np_arr2 = np.array([[1,3,5], [5,9,12]])
np_arr2

array([[ 1,  3,  5],
       [ 5,  9, 12]])

In [17]:
# 3차원 배열
np_arr3 = np.array([[[0, 2, 4], [8, 10, 12]], [[1, 3, 5], [7, 9, 12]]])
np_arr3

array([[[ 0,  2,  4],
        [ 8, 10, 12]],

       [[ 1,  3,  5],
        [ 7,  9, 12]]])

In [19]:
#  파이썬 기본 리스트(배열)
list1 = [1, 3, 5]
list1

[1, 3, 5]

In [20]:
# [1, 3, 5]. [1, 3, 5] 는 튜플로 1차원 배열이 두 개 만들어짐 -> numpy에서는 허용 안됨
# [[1, 3, 5], [1, 3, 5]] 2차원 배열
list2 = [[1, 3, 5], [1, 3, 5]]
list2

[[1, 3, 5], [1, 3, 5]]

In [21]:
# 길이 4의 1차원 배열을 전부 0으로 채울 것
np_arr4 = np.zeros(4)
np_arr4

array([0., 0., 0., 0.])

In [23]:
np_arr5 = np.zeros([2, 3])
np_arr5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
# 랜덤은 활용도 있음
np.random.randn(2, 3)

array([[ 0.5416762 ,  0.53995463, -2.16042489],
       [ 1.53115304,  0.55092539, -0.51044852]])

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# list(np.arange(10)), np.array(list(range(10)))과 동일
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
np_arr7 = np.arange(10)
np_arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np_arr7 * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [39]:
np_arr7 / 4

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25])

In [40]:
np_arr7 // 2

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4], dtype=int32)

In [41]:
# numpy 배열은 + 더하기 연산
np_arr7 + np_arr7

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
# 파이썬 리스트 + concat(두 리스트를 합침)
list(np_arr7) + list(np_arr7)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [43]:
# 비교연산
(np_arr7 + np_arr7) < 9

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [44]:
(np_arr7 + np_arr7) != 10

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True])

In [46]:
# 조회
np_arr7[1]

1

In [47]:
# 인덱스 크기를 벗어나면 IndexError 예외 발생
np_arr7[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [48]:
np_arr7[np_arr7 < 5]

array([0, 1, 2, 3, 4])

In [50]:
list2 = list(range(10))
list2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [51]:
[x for x in range(10) if x < 5] # 리스트 내포

[0, 1, 2, 3, 4]

In [52]:
np_arr7[3:9] # 뒤에 인덱스는 항상 -1

array([3, 4, 5, 6, 7, 8])

In [53]:
# 2차원 배열에서 값 조회
np_arr2[1][2]

12

In [57]:
np_arr2[1, 2] = 9
np_arr2

array([[1, 3, 5],
       [5, 9, 9]])

In [58]:
# 값 변경(치환)
np_arr7[np_arr7 < 5] = 100
np_arr7

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

#### 속성

- shape, dtype, T

In [59]:
# 1차원
np_arr1.shape

(3,)

In [60]:
# 2차원
np_arr2.shape

(2, 3)

In [61]:
np_arr2.dtype

dtype('int32')

In [62]:
# Pivot
np_arr2.T

array([[1, 5],
       [3, 9],
       [5, 9]])

In [63]:
np_arr2.T.shape

(3, 2)

#### 기타 함수

In [64]:
np_arr8 = np.arange(10)
np_arr8

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
# 평균
np_arr8.mean()

4.5

In [66]:
# 합계
np_arr8.sum()

45

In [68]:
# 누적 합계
np_arr8.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [69]:
np_arr9 = np.random.randn(10)
np_arr9

array([-0.39949499,  0.7630447 ,  0.20892152,  0.25601117,  0.57699784,
       -0.93447217, -0.26814529,  1.86257266, -0.19074631,  1.00305633])

In [74]:
# 오름차순 정렬
np_arr9.sort()
np_arr9

array([-0.93447217, -0.39949499, -0.26814529, -0.19074631,  0.20892152,
        0.25601117,  0.57699784,  0.7630447 ,  1.00305633,  1.86257266])

In [75]:
# 내림차순 정렬
-np.sort(-np_arr9)

array([ 1.86257266,  1.00305633,  0.7630447 ,  0.57699784,  0.25601117,
        0.20892152, -0.19074631, -0.26814529, -0.39949499, -0.93447217])

#### 테스트용 데이터프레임 예제

In [102]:
# 테스트용 더미데이터프레임 만들기
# 판다스와 조합해서 생성
size = 10
df = pd.DataFrame({
    'class': [['A', 'B', 'C', 'D', 'F'][np.random.randint(0, 5)] for i in range(0, size)],
    'year': [np.random.randint(2010, 2024) for i in range(0, size)],
    'month': [np.random.randint(1, 13) for i in range(0, size)],
    'val1': [np.random.randint(1, 11) for i in range(0, size)],
    'val2': [np.random.randint(100, 1000) for i in range(0, size)],
    'val3': [np.random.randint(10000, 20000) for i in range(0, size)]
})

df

class  year  month  val1  val2   val3
0     A  2023     12     8   705  11362
1     B  2015     10     9   762  19431
2     B  2017      4     4   590  15408
3     B  2013      9     5   839  18226
4     F  2010      7     8   822  15440
5     B  2012      6     4   156  15504
6     B  2016      3     3   761  12977
7     C  2016      8     8   534  13421
8     F  2014      9     7   286  17909
9     A  2013      2     8   862  12676

In [104]:
df.shape

(10, 6)

In [105]:
df.dtypes

class    object
year      int64
month     int64
val1      int64
val2      int64
val3      int64
dtype: object

In [106]:
df.T

0      1      2      3      4      5      6      7      8      9
class      A      B      B      B      F      B      B      C      F      A
year    2023   2015   2017   2013   2010   2012   2016   2016   2014   2013
month     12     10      4      9      7      6      3      8      9      2
val1       8      9      4      5      8      4      3      8      7      8
val2     705    762    590    839    822    156    761    534    286    862
val3   11362  19431  15408  18226  15440  15504  12977  13421  17909  12676